name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cria arquivo a ser transferido
      run: echo "Teste" > arquivo.txt
    - name: gera o arquivo id_rsa
      run: echo ${{ secrets.CHAVE }} > id_rsa
    - name: upload do arquivo
      run: scp -i id_rsa arquivo.txt rafante2@35.232.98.141
