name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Hello World!" > teste.txt
    - name: printa
      run: echo ${{secrets.chave}} > segredo
    - name: printa o segredo
      run: echo segredo
