name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cria a chave rsa
      env:
        UMA_CHAVE: ${{secrets.CHAVE}}
      run: | 
        echo ${UMA_CHAVE} > id_rsa
        cat id_rsa
        echo arquivo_bobo.txt
        scp -i id_rsa arquivo_bobo.txt rafante2@35.232.98.141:/home/rafante2/teste
