name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cria arquivo a ser transferido
      run: echo "Teste" > arquivo.txt
    - name: gera o arquivo id_rsa
      run: echo ${{ secrets.CHAVE }} >id_rsa
    - name: Copia o arquivo
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.CHAVE }}
        source: "arquivo.txt,arquivo.txt"
        target: "/home/rafante2/teste"
