name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Hello World!" > teste.txt
    - name: Run a multi-line script
      run: echo ${{secrets.chave}} > id_rsa
    - name: printa
      run: echo ${{secrets.chave}}
    - name: Teste
      run: scp -i id_rsa teste.txt rafante2@35.232.98.141
