name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cria a chave rsa
      env:
        UMA_CHAVE: ${{secrets.CHAVE}}
    - name: cria um arquivo
      run: echo "Teste" > arquivo.txt
    - name: Copia o arquivo
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "arquivo.txt,arquivo.txt"
        target: "/home/rafante2/teste"
